src/main/java/com/care/model/Member.java
package com.care.model;

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

public class Member extends BaseModel {
    private long id;
    private String firstName;
    private String lastName;
    private String phone;
    private MemberType memberType;
    private String email;
    private String address;
    private String zipCode;
    private Status status = Status.ACTIVE;
    private Timestamp lastModified;
    private String password;
    private Set<Token> tokens = new HashSet<>();

    private static final Member EMPTY_MEMBER = new Member();

    public Member() {
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public MemberType getMemberType() {
        return memberType;
    }

    public void setMemberType(MemberType memberType) {
        this.memberType = memberType;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getZipCode() {
        return zipCode;
    }

    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    public Timestamp getLastModified() {
        return lastModified;
    }

    public void setLastModified(Timestamp lastModified) {
        this.lastModified = lastModified;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Set<Token> getTokens() {
        return tokens;
    }

    public void setTokens(Set<Token> tokens) {
        this.tokens = tokens;
    }

    public static Member emptyMember() {
        return EMPTY_MEMBER;
    }

    public boolean isSeeker(){
        return memberType == MemberType.SEEKER;
    }

    public boolean isSitter(){
        return memberType == MemberType.SITTER;
    }

    public boolean isEmpty(){
        return this == EMPTY_MEMBER;
    }

    public boolean isActive(){
        return getStatus() == Status.ACTIVE;
    }


}

src/main/java/com/care/model/Seeker.java
package com.care.model;

import java.util.HashSet;
import java.util.Set;

public class Seeker extends Member{

    private long id;
    private int numberOfChildren;
    private String spouseName;
    private Set<Job> jobs = new HashSet<>();

    private static final Seeker EMPTY_SEEKER = new Seeker();

    public Seeker() {
    }

    @Override
    public long getId() {
        return id;
    }

    @Override
    public void setId(long id) {
        this.id = id;
    }

    public int getNumberOfChildren() {
                return numberOfChildren;
        }

    public void setNumberOfChildren(int numberOfChildren) {
         this.numberOfChildren = numberOfChildren;
    }

    public String getSpouseName() {
                return spouseName;
        }

    public void setSpouseName(String spouseName) {
                this.spouseName = spouseName;
        }

    public Set<Job> getJobs() {
        return jobs;
    }

    public void setJobs(Set<Job> jobs) {
        this.jobs = jobs;
    }

    public static Seeker emptySeeker(){
        return EMPTY_SEEKER;
    }

//    public postJob(){
//
//    }

    public int closeAllJobs(){
        for(Job job : jobs){
            if (job.getStatus() == Status.ACTIVE){
                job.close();
                job.setStatus(Status.EXPIRED);
            }
        }
        return 1;
    }

    public int closeAccount(){
        closeAllJobs();
        this.setStatus(Status.CLOSED);
        this.setEmail(getEmail() + "CLOSED" + getId());
        return 1;
    }

}

src/main/java/com/care/controller/HomeAction.java
package com.care.controller;

import com.care.filter.HibernateFilter;
import com.care.model.Member;
import com.care.model.MemberType;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.util.logging.Logger;

public class HomeAction extends Action {
    Logger logger = Logger.getLogger("HomeAction");

    @Override
    public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception {
        Member member = (Member) request.getSession().getAttribute(ControllerUtil.CURRENT_USER);
        MemberType memberType = member.getMemberType();
        request.setAttribute(HibernateFilter.END_OF_CONVERSATION_FLAG, "True");
        return mapping.findForward(memberType.name().toLowerCase());
    }
}

src/main/webapp/seeker/header.jsp
<style media="screen">
        .right{
            float: right;
        }
</style>
<script type="text/javascript">
                function confirmation(form, msg) {
                    if(window.confirm("Are you sure you want to " + msg)){
                        form.submit();
                    }
                }
</script>

        <h2>Welcome ${CURRENT_USER.email}</h2>
        <div class="left">
            <form class="" action="${pageContext.request.contextPath}/member/home.do" method="post">
                 <input type="submit" name="home" value="Home"/>
            </form>
        </div>

        <div class="right">
            <form  action="${pageContext.request.contextPath}/member/logout.do" method="post">
                <input type="button" name="logout" value="Log Out" onclick="confirmation(this.form, 'log out')">
            </form>

            <form  action="${pageContext.request.contextPath}/member/updatePassword.jsp" method="post">
                <input type="submit" name="Update Password" value="Update Password">
            </form>
        </div>

src/main/webapp/seeker/home.jsp
<%@ page contentType="text/html;charset=UTF-8" errorPage = "../ErrorPage.jsp" language="java" %>
<%@ taglib prefix="c"
       uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib uri="http://struts.apache.org/tags-html"
           prefix="html" %>
<%@ taglib prefix="fn"
       uri="http://java.sun.com/jsp/jstl/functions" %>
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </head>
    <body>


      <jsp:include page="/member/header.jsp"/>
      <font color="green">
      <c:choose>
          <c:when test="${param.login eq 'true'}">

          </c:when>
          <c:when test="${param.post eq 'true'}">
              <h2>Job posted successfully </h2>
          </c:when>
          <c:when test="${param.delete eq 'true'}">
              <h2>Job Deleted</h2>
          </c:when>
          <c:when test="${param.jobedit eq 'true'}">
               <h2>Job Edited</h2>
          </c:when>
          <c:when test="${param.pass eq 'true'}">
                <h2>Password updated</h2>
          </c:when>
          <c:when test="${param.profile eq 'true'}">
              <h2>Profile updated</h2>
          </c:when>
      </c:choose>


        </font>

      <%-- <jsp:include page="/footer.jsp"/> --%>
    </body>
</html>

src/main/webapp/seeker/postJob.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c"
       uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib uri="http://struts.apache.org/tags-html"
           prefix="html" %>
<%@ taglib prefix="fn"
       uri="http://java.sun.com/jsp/jstl/functions" %>
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </head>
    <body>

     <jsp:include page="/member/header.jsp"/>
     <div class="container" style="max-width:500px">

     <html:form action="/seeker/capturePostJob" method="post">
            <div class="form-group">
                 <label>Job Title* </label>
                 <html:text property="title" styleClass="form-control"/>
                 <font color="red"> <html:errors property="title" /> </font>
            </div>
            <div class="form-group">
                 <label>Hourly Pay* </label>
                 <html:text property="hourlyPay" styleClass="form-control" />
                 <font color="red"> <html:errors property="hourlyPay" /> </font>
            </div>
            <div class="form-group">
                 <label>Start Date*</label>
                 <input type="date" name="startDate" value="${jobForm.startDate}" class="form-control"/>
                 <font color="red"> <html:errors property="startDate" /> </font>
            </div>
            <div class="form-group">
                 <label>Start Time*</label>
                 <input type="time" name="startTime" value="${jobForm.startTime}" class="form-control"/>
                 <font color="red"> <html:errors property="startTime" /> </font>
            </div>
            <div class="form-group">
                 <label>End Date*</label>
                 <input type="date" name="endDate" value="${jobForm.endDate}" class="form-control"/>
                 <font color="red"> <html:errors property="endDate" /> </font>
            </div>
            <div class="form-group">
                 <label>End Time*</label>
                 <input type="time" name="endTime" value="${jobForm.endTime}" class="form-control"/>
                 <font color="red"> <html:errors property="endTime" /> </font>
            </div>
         <html:submit property="submit" styleClass="form-control" value="Submit"/>
     </html:form>
     </div>
    </body>
    <%-- <jsp:include page="/footer.jsp"/> --%>
</html>

src/main/webapp/seeker/showAndEditJob.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c"
       uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib uri="http://struts.apache.org/tags-html"
           prefix="html" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>

<%@ taglib prefix="fn"
       uri="http://java.sun.com/jsp/jstl/functions" %>
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </head>
    <body>
    <jsp:include page="/member/header.jsp"/>
    <div class="container" style="max-width:500px">
        <html:form action="/seeker/captureEditJob" method="post">
                <div class="form-group">
                     <label>Job Title</label>
                     <html:text property="title" styleClass="form-control"/>
                     <font color="red"> <html:errors property="title" /> </font>
                </div>
                <div class="form-group">
                     <label>Hourly Pay</label>
                     <html:text property="hourlyPay" styleClass="form-control"/>
                     <font color="red"> <html:errors property="hourlyPay" /> </font>
                </div>
                <div class="form-group">
                     <label>Start Date*</label>
                     <input type="date" name="startDate" value="${jobForm.startDate}" class="form-control"/>
                     <font color="red"> <html:errors property="startDate" /> </font>
                </div>
                <div class="form-group">
                     <label>Start Time*</label>
                     <input type="time" name="startTime" value="${jobForm.startTime}" class="form-control"/>
                     <font color="red"> <html:errors property="startTime" /> </font>
                </div>
                <div class="form-group">
                     <label>End Date*</label>
                     <input type="date" name="endDate" value="${jobForm.endDate}" class="form-control"/>
                     <font color="red"> <html:errors property="endDate" /> </font>
                </div>
                <div class="form-group">
                     <label>End Time*</label>
                     <input type="time" name="endTime" value="${jobForm.endTime}" class="form-control"/>
                     <font color="red"> <html:errors property="endTime" /> </font>
                </div>

            <html:hidden property="id" />
            <html:submit property="submit" styleClass="form-control" value="Submit"/>
        </html:form>
     </div>
    </body>
    <%-- <jsp:include page="/footer.jsp"/> --%>
</html>

src/main/webapp/seeker/showMyJobs.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c"
       uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib prefix="fn"
       uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib uri="http://struts.apache.org/tags-html"
           prefix="html" %>
<!DOCTYPE html>

<html lang="en" dir="ltr">
        <head>
            <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
              <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
              <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
            <script type="text/javascript">
                function confirmDeletion(form) {
                    if(window.confirm("Are you sure you want to Delete this Job")){
                        form.submit();
                    }
                }
            </script>
        </head>
        <body>

             <jsp:include page="/member/header.jsp"/>

             <div class="container">
             <font color="green">
                 <c:choose>
                     <c:when test="${param.jobedit eq 'true'}">
                        <h2>Edit Successful</h2>
                     </c:when>
                     <c:when test="${param.delete eq 'true'}">
                        <h2>Delete Successful</h2>
                     </c:when>
                 </c:choose>
             </font>
             <c:choose>
                <c:when test="${fn:length(myJobs) > 0}">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <td>Title</td>
                                <td>Status</td>
                                <td>Hourly Pay</td>
                                <td>Start Date</td>
                                <td>End Date</td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                        </thead>
                        <c:forEach var="job" items="${myJobs}">
                        <tr>
                            <td>${job.title}</td>
                            <td>${job.status}</td>
                            <td>${job.hourlyPay}</td>
                            <fmt:formatDate var="startDate" value="${job.startDateTime}" pattern="yyyy-MM-dd hh:mm"/>
                            <td>${startDate}</td>
                            <fmt:formatDate var="endDate" value="${job.endDateTime}" pattern="yyyy-MM-dd hh:mm"/>
                            <td>${endDate}</td>
                            <td>
                                <c:if test="${job.status != 'EXPIRED'}">
                                <form action="${pageContext.request.contextPath}/seeker/showJobToEdit.do" method="get">
                                    <input type="hidden" name="id" value="${job.id}">
                                    <input type="submit" name="" value="Edit">
                                </form>
                                </c:if>
                            </td>
                            <td>
                                <form action="${pageContext.request.contextPath}/seeker/deleteJob.do" method="get">
                                    <input type="hidden" name="id" value="${job.id}">
                                    <input type="button" name="" value="Delete" onclick="confirmDeletion(this.form)">
                                </form>
                            </td>
                            <td>
                               <c:if test="${job.status != 'EXPIRED'}">
                                <form action="${pageContext.request.contextPath}/seeker/viewApplications.do" method="get">
                                    <input type="hidden" name="id" value="${job.id}">
                                    <input type="submit" name="" value="View Applications">
                                </form>
                                </c:if>
                            </td>
                        </tr>
                    </c:forEach>
                    </table>
                </c:when>
                <c:otherwise>
                    <font color="red"> <h3>No jobs to Show</h3> </font>
                </c:otherwise>
             </c:choose>

            <c:if test="${fn:length(myJobs) > 0}">

            </c:if>
</div>
        </body>
        <%-- <jsp:include page="/footer.jsp"/> --%>
</html>

src/main/webapp/seeker/viewApplications.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c"
       uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib prefix="fn"
       uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib uri="http://struts.apache.org/tags-html"
           prefix="html" %>
<!DOCTYPE html>
<html>
<head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
    <body>

    <jsp:include page="/member/header.jsp"/>
        <div class="container">

        <c:choose>
            <c:when test="${fn:length(getApplications) > 0}">
                <center><h2>${getApplications[0].job.title}</h2></center>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <td>First Name</td>
                            <td>Last Name</td>
                            <td>Status</td>
                            <td>Expected Pay</td>
                        </tr>
                    </thead>
                    <c:forEach var="app" items="${getApplications}">
                        <tr>
                            <td>${app.sitter.firstName}</td>
                            <td>${app.sitter.lastName}</td>
                            <td>${app.status}</td>
                            <td>${app.expectedPay}</td>
                        </tr>
                    </c:forEach>
                </table>
            </c:when>
            <c:otherwise>
                <font color="red"> <h3>No Applications to Show</h3> </font>
            </c:otherwise>
        </c:choose>
        </div>
    </body>
    <%-- <jsp:include page="/footer.jsp"/> --%>
</html>