src/main/java/com/care/form/ApplicationForm.java
package com.care.form;

import com.care.annotation.DecimalNumber;
import com.care.annotation.NotEmpty;
import com.care.annotation.Range;
import com.care.validation.FormValidator;
import org.apache.struts.action.ActionErrors;

import java.lang.reflect.InvocationTargetException;
import java.util.logging.Logger;

import javax.servlet.http.HttpServletRequest;

public class ApplicationForm extends BaseForm {

    Logger logger = Logger.getLogger("ApplicationForm");

    private String jobId;
    private String sitterId;
    private String expectedPay;

    public String getJobId() {
        return jobId;
    }

    public void setJobId(String jobId) {
        this.jobId = jobId;
    }

    public String getSitterId() {
        return sitterId;
    }

    public void setSitterId(String sitterId) {
        this.sitterId = sitterId;
    }

    @NotEmpty
    @DecimalNumber
    @Range(min = 1, max = 1000, message = "errors.amount.size")
    public String getExpectedPay() {
        return expectedPay;
    }

    public void setExpectedPay(String expectedPay) {
        this.expectedPay = expectedPay;
    }

    @Override
    public ActionErrors validateCustom(HttpServletRequest request) {
        ActionErrors errors = new ActionErrors();
        try {
            FormValidator.validate(this, errors);
        } catch (InvocationTargetException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        }
        return errors;
    }

    @Override
    public String toString() {
        return "ApplicationForm{" +
                "jobId='" + jobId + '\'' +
                ", sitterId='" + sitterId + '\'' +
                ", expectedPay='" + expectedPay + '\'' +
                '}';
    }
}

src/main/java/com/care/form/BaseForm.java
package com.care.form;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import javax.servlet.http.HttpServletRequest;

public abstract class BaseForm extends ActionForm {
    public abstract ActionErrors validateCustom(HttpServletRequest request);

    @Override
    public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) {
        return validateCustom(request);
    }
}

src/main/java/com/care/form/EditProfileForm.java
package com.care.form;

import com.care.annotation.*;
import com.care.annotation.Number;
import com.care.controller.ControllerUtil;
import com.care.model.Member;
import com.care.service.AccountService;
import com.care.service.AccountServiceImpl;
import com.care.service.ServiceFactory;
import com.care.validation.FormValidator;
import org.apache.commons.lang3.StringUtils;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMessage;

import java.lang.reflect.InvocationTargetException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.servlet.http.HttpServletRequest;

@Flow(flowId = "getMemberType")
public class EditProfileForm extends BaseForm {
    private Logger logger = Logger.getLogger("PutProfileInfo");

    private String email;
    private String firstName;
    private String lastName;
    private String zipCode;
    private String memberType;
    private String address;
    private String phone;
    private String spouseName;
    private String numberOfChildren;
    private String expectedPay;
    private String experience;
    private String id;

    @NotEmpty
    @Email
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }


    @FlowCheck(flow = "SITTER")
    @NotEmpty
    @DecimalNumber
    @Range(min=1, max = 1000, message = "errors.amount.size")
    public String getExpectedPay() {
        return expectedPay;
    }

    public void setExpectedPay(String expectedPay) {
        this.expectedPay = expectedPay;
    }

    @FlowCheck(flow = "SITTER")
    @NotEmpty
    @Number
    @Range(min = 0, max = 100, message = "errors.experience.size")
    public String getExperience() {
        return experience;
    }

    public void setExperience(String experience) {
        this.experience = experience;
    }

    @Name
    public String getSpouseName() {
        return spouseName;
    }

    public void setSpouseName(String spouseName) {
        this.spouseName = spouseName;
    }

    @Number
    @Range(min = 0, max = 100, message = "errors.children.size")
    public String getNumberOfChildren() {
        return numberOfChildren;
    }

    public void setNumberOfChildren(String numberOfChildren) {
        this.numberOfChildren = numberOfChildren;
    }

    @NotEmpty
    @Name
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @NotEmpty
    @Name
    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @NotEmpty
    @Zipcode
    public String getZipCode() {
        return zipCode;
    }

    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    public String getMemberType() {
        return memberType;
    }

    public void setMemberType(String memberType) {
        this.memberType = memberType;
    }

    @NotEmpty
    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @NotEmpty
    @Phone
    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }


    @Override
    public ActionErrors validateCustom(HttpServletRequest request) {
        Member member = (Member) request.getSession().getAttribute(ControllerUtil.CURRENT_USER);
        ActionErrors errors = new ActionErrors();
        try {
            FormValidator.validate(this, errors);
        } catch (InvocationTargetException e) {
            logger.log(Level.SEVERE, "While validating", e);
        } catch (IllegalAccessException e) {
            logger.log(Level.SEVERE, "While validating", e);
        }

        if (! errors.isEmpty()){
            return errors;
        }
        // The below lines may not be required. Removal required [todo]
        try {
            if (member != null && member.isSitter()){
                if (StringUtils.isBlank(expectedPay)){
                    errors.add("expectedPay", new ActionMessage("errors.notnull", "expectedPay"));
                }
                if (StringUtils.isBlank(experience)){
                    errors.add("experience", new ActionMessage("errors.notnull", "experience"));
                }
            }
        } catch (Exception e) {
            // this property is not being printed as error.
            errors.add("flow", new ActionMessage("errors.invalid"));
        }
        /*
        Check if the email entered is already in use
         */
        AccountService accountService = ServiceFactory.get(AccountServiceImpl.class);
       // errors.properties()
        // if Id is null then assume it is for Registration.
        if (errors.isEmpty()){
            Member member1 ;
            try {
                member1 = accountService.getMember(getEmail());
            } catch (Exception e) {
                member1 = Member.emptyMember();
            }
            // Only if there is already a member registered.
            if (! member1.isEmpty()){
                // it is for registration.
                //String ID = String.valueOf(member1.getId());
                if (member == null){
                    errors.add("email", new ActionMessage("errors.email.exist", "Email"));
                }

                //This will take care of Edit Email, Checks if the emailId is unchanged.
                //equals method should be used.
                else if( member1.getId() != member.getId()){
                    errors.add("email", new ActionMessage("errors.email.exist", "Email"));
                }
            }
        }
        if (StringUtils.isBlank(numberOfChildren) && errors.isEmpty()){
            numberOfChildren="0";
        }
        return errors;
    }
}

src/main/java/com/care/form/EmailForm.java
package com.care.form;

import com.care.annotation.Email;
import com.care.annotation.NotEmpty;
import com.care.service.AccountService;
import com.care.service.AccountServiceImpl;
import com.care.service.ServiceFactory;
import com.care.validation.FormValidator;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMessage;

import java.lang.reflect.InvocationTargetException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.servlet.http.HttpServletRequest;

public class EmailForm extends BaseForm {

    private Logger logger = Logger.getLogger(this.getClass().getName());
    private String email;

    @NotEmpty
    @Email
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public ActionErrors validateCustom(HttpServletRequest request) {
        ActionErrors errors = new ActionErrors();
        try {
            FormValidator.validate(this, errors);
            // validate if the email exist in the DB.
            AccountService accountService = ServiceFactory.get(AccountServiceImpl.class);
            if (errors.isEmpty()){
                try{
                    accountService.getMember(email);
                }catch (Exception e){
                    errors.add("email", new ActionMessage("errors.email.notexist", "Email"));
                }
            }

        } catch (InvocationTargetException e) {
            logger.log(Level.SEVERE, "Invok", e);
        } catch (IllegalAccessException e) {
            logger.log(Level.SEVERE, "Invok", e);
        }
        return errors;
    }
}

src/main/java/com/care/form/LoginForm.java
package com.care.form;

import com.care.annotation.Email;
import com.care.annotation.NotEmpty;
import com.care.validation.FormValidator;
import org.apache.struts.action.ActionErrors;

import java.lang.reflect.InvocationTargetException;

import javax.servlet.http.HttpServletRequest;

public class LoginForm extends BaseForm {
    private String email;
    private String password;

    @NotEmpty
    @Email
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @NotEmpty
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String toString() {
        return "LoginForm{" +
                "email='" + email + '\'' +
                ", password='" + password + '\'' +
                '}';
    }

    @Override
    public ActionErrors validateCustom(HttpServletRequest request) {
        ActionErrors errors = new ActionErrors();
        try {
            FormValidator.validate(this, errors);
        } catch (InvocationTargetException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        }
        return errors;
    }

}

src/main/java/com/care/form/PasswordUpdateForm.java
package com.care.form;

import com.care.annotation.NotEmpty;
import com.care.controller.ControllerUtil;
import com.care.model.Member;
import com.care.service.Hash;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMessage;

import javax.servlet.http.HttpServletRequest;

public class PasswordUpdateForm extends PasswordResetForm {
    private String currentPassword;

    @NotEmpty
    public String getCurrentPassword() {
        return currentPassword;
    }

    public void setCurrentPassword(String currentPassword) {
        this.currentPassword = currentPassword;
    }

    @Override
    public ActionErrors validateCustom(HttpServletRequest request) {
        Member member = (Member) request.getSession().getAttribute(ControllerUtil.CURRENT_USER);
        ActionErrors errors =  super.validateCustom(request);
        if (! errors.isEmpty()){
            return errors;
        }
        if (! Hash.createHash(currentPassword).equals(member.getPassword())){
            errors.add("currentPassword", new ActionMessage("errors.password.incorrect"));
        }
        return errors;
    }
}

src/main/java/com/care/form/RegistrationForm.java
package com.care.form;

import com.care.annotation.Flow;
import com.care.annotation.NotEmpty;
import com.care.annotation.Password;
import com.care.annotation.Size;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMessage;

import java.util.logging.Logger;

import javax.servlet.http.HttpServletRequest;
@Flow(flowId = "getMemberType")
public class RegistrationForm extends EditProfileForm {

    private Logger logger = Logger.getLogger("RegistrationForm");

    private String password;
    private String password2;

    @NotEmpty
    @Password(message = "errors.password")
    @Size(min=5, max=100, message = "errors.password.size")
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @NotEmpty
    public String getPassword2() {
        return password2;
    }

    public void setPassword2(String password2) {
        this.password2 = password2;
    }

    @Override
    public ActionErrors validateCustom(HttpServletRequest request) {
        ActionErrors errors = super.validateCustom(request);

        if (! errors.isEmpty()){
            return errors;
        }
        if(! password.equals(password2)){
            errors.add("password2", new ActionMessage("errors.password.mismatch"));
        }

        return errors;
    }
}

src/main/java/com/care/model/Application.java
/*
        Bean class corresponding to Application.
*/

package com.care.model;

import java.sql.Timestamp;

public class Application extends BaseModel {

    private long id;
    private double expectedPay;
    private Status status = Status.ACTIVE;
    private Timestamp dateCreated;
    private Timestamp lastModified;
    private Job job;
    private Sitter sitter;

    private static final Application EMPTY_APPLICATION = new Application();

    public Application() {

    }

    public Job getJob() {
        return job;
    }

    public void setJob(Job job) {
        this.job = job;
    }

    public Sitter getSitter() {
        return sitter;
    }

    public void setSitter(Sitter sitter) {
        this.sitter = sitter;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public double getExpectedPay() {
        return expectedPay;
    }

    public void setExpectedPay(double expectedPay) {
        this.expectedPay = expectedPay;
    }

    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    public Timestamp getDateCreated() {
        return dateCreated;
    }

    public void setDateCreated(Timestamp dateCreated) {
        this.dateCreated = dateCreated;
    }

    public Timestamp getLastModified() {
        return lastModified;
    }

    public void setLastModified(Timestamp lastModified) {
        this.lastModified = lastModified;
    }

    public static Application emptyApplication() {
        return EMPTY_APPLICATION;
    }

    public boolean isEmpty(){
        return this == EMPTY_APPLICATION;
    }

    public boolean isClosed() {
        return status == Status.CLOSED;
    }

    public boolean isActive(){
        return status == Status.ACTIVE;
    }

    public void close(){
        status = Status.CLOSED;
    }


}

src/main/java/com/care/model/BaseModel.java
package com.care.model;

import java.io.Serializable;

public abstract class BaseModel implements Serializable {
}

src/main/java/com/care/controller/ChangePasswordAction.java
package com.care.controller;

import com.care.filter.HibernateFilter;
import com.care.form.PasswordResetForm;
import com.care.form.PasswordUpdateForm;
import com.care.model.Member;
import com.care.service.AuthenticationService;
import com.care.service.AuthenticationServiceImpl;
import com.care.service.OperationStatus;
import com.care.service.ServiceFactory;
import org.apache.struts.action.*;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Logger;

public class ChangePasswordAction extends Action {
    Logger logger = Logger.getLogger("ChangePasswordAction");

    @Override
    public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception {
        Member member = (Member)request.getSession().getAttribute(ControllerUtil.CURRENT_USER);

        String page = "success";
        PasswordUpdateForm passwordUpdateForm = (PasswordUpdateForm) form;
        passwordUpdateForm.setId(String.valueOf(member.getId()));

        AuthenticationService authenticationService = ServiceFactory.get(AuthenticationServiceImpl.class);
        OperationStatus operationStatus  =
                authenticationService.updatePassword(member, passwordUpdateForm);
        if (operationStatus == OperationStatus.SUCCESS){
            request.setAttribute(HibernateFilter.END_OF_CONVERSATION_FLAG, "True");
        }
        return mapping.findForward(operationStatus.name().toLowerCase());
    }
}

src/main/webapp/404error.jsp
<%@ page contentType="text/html;charset=UTF-8" isErrorPage = "true" language="java" %>
<%@ taglib prefix="c"
       uri="http://java.sun.com/jsp/jstl/core" %>

<%@ taglib prefix="fn"
       uri="http://java.sun.com/jsp/jstl/functions" %>

<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <h2>${errorMessage}</h2>
        <h1>The rquested page could not be found</h1>
        <a href="${pageContext.request.contextPath}/member/home.do">Click here to go back</a>
    </body>
</html>

src/main/webapp/ErrorPage.jsp
<%@ page contentType="text/html;charset=UTF-8" isErrorPage = "true" language="java" %>
<%@ taglib prefix="c"
       uri="http://java.sun.com/jsp/jstl/core" %>

<%@ taglib prefix="fn"
       uri="http://java.sun.com/jsp/jstl/functions" %>

<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <h1>Something bad happened</h1>
        <h2>${errorMessage}</h2>
        <a href="${pageContext.request.contextPath}/member/home.do">Click here to go back</a>
    </body>
</html>

src/main/webapp/badRequest.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c"
           uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib uri="http://struts.apache.org/tags-html"
           prefix="html" %>
<%@ taglib prefix="fn"
           uri="http://java.sun.com/jsp/jstl/functions" %>

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>

        <style type="text/css">
            form {
                text-align: center;
            }
            input {
                width: 100px;
            }
            .right{
                float:right;
            }
        </style>
    </head>
    <body>
        <div class="form1" al>
            <h1>Bad Request</h1>
            <a href="${pageContext.request.contextPath}/member/home.do">Click here to go back</a>
        </div>
    </body>
</html>

src/main/webapp/errors.jsp
<%@ page contentType="text/html;charset=UTF-8" isErrorPage = "true" language="java" %>
<%@ taglib prefix="c"
       uri="http://java.sun.com/jsp/jstl/core" %>

<%@ taglib prefix="fn"
       uri="http://java.sun.com/jsp/jstl/functions" %>

<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <h1>Something bad happened</h1>
        <h2>${errorMessage}</h2>
        <a href="${pageContext.request.contextPath}/member/home.do">Click here to go back</a>
    </body>
</html>

src/main/webapp/footer.jsp
<style>
.footer {
   position: fixed;
   left: 0;
   bottom: 0;
   width: 100%;
   background-color: red;
   color: white;
   text-align: center;
}
</style>

<div class="container footer">
    <p>
        contact: contactus@caregivers.com
    </p>

</div>

src/main/webapp/header.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c"
       uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib uri="http://struts.apache.org/tags-html"
           prefix="html" %>
<%@ taglib prefix="fn"
       uri="http://java.sun.com/jsp/jstl/functions" %>
<style media="screen">
        .right{
            float: right;
        }
</style>
<script type="text/javascript">
                function confirmation(form, msg) {
                    if(window.confirm("Are you sure you want to " + msg)){
                        form.submit();
                    }
                }
</script>

        <h2>Welcome ${currentUser.email}</h2>
        <div class="left">
            <form class="" action="${pageContext.request.contextPath}/member/home.do" method="post">
                 <input type="submit" name="home" value="Home">
            </form>
        </div>

        <div class="right">
            <form class="" action="${pageContext.request.contextPath}/member/logout.do" method="post">
                <input type="button" name="logout" value="Log Out" onclick="confirmation(this.form, 'log out')">
            </form>
            <form class="" action="${pageContext.request.contextPath}/member/updatePassword.jsp" method="post">
                <input type="submit" name="Update Password" value="Update Password">
            </form>
        </div>

src/main/webapp/index.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c"
           uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib uri="http://struts.apache.org/tags-html"
           prefix="html" %>
<%@ taglib prefix="fn"
           uri="http://java.sun.com/jsp/jstl/functions" %>

<!DOCTYPE html>
<html>
    <head>
    </head>

    <body>
        <c:redirect url = "/visitor/login.do"/>
    </body>
</html>

src/main/webapp/login.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c"
           uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib uri="http://struts.apache.org/tags-html"
           prefix="html" %>
<%@ taglib prefix="fn"
           uri="http://java.sun.com/jsp/jstl/functions" %>

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

        <style type="text/css">
            .right{
                float:right;
            }
        </style>
    </head>
    <body>
        <div class="container" style="max-width:500px">
            <h1>Welcome to Home Job Marketplace</h1>

                <c:choose>
                    <c:when test="${param.closed eq 'true'}">
                       <font color="green"><h2>Account Closed</h2></font>
                    </c:when>
                    <c:when test="${param.login eq 'not'}">
                       <font color="red"> <h2>You must log in first</h2></font>
                    </c:when>
                    <c:when test="${param.login eq 'false'}">
                        <font color="red"><h2>Incorrect Email or password</h2></font>
                    </c:when>
                    <c:when test="${param.pass eq 'true'}">
                        <font color="green"><h2>Password reset successful</h2></font>
                    </c:when>
                    <c:when test="${param.mail eq 'true'}">
                        <font color="green"><h2>Password reset link sent</h2></font>
                    </c:when>
                    <c:when test="${param.pass eq 'failed'}">
                        <font color="red"><h2>Password reset Failed</h2></font>
                    </c:when>
                    <c:when test="${param.token eq 'invalid'}">
                        <font color="red"><h2>Invalid Token</h2></font>
                    </c:when>
                </c:choose>

            <html:form action="/visitor/captureLogin" method="post">
                <div class="form-group">
                    <label>Email</label>
                    <html:text property="email" styleClass="form-control" /><br>
                    <font color="red"> <html:errors property="email" /> </font>
                </div>
                <div class="form-group">
                    <label>Password</label>
                    <input type="password" name="password" class="form-control" /><br>
                    <font color="red"> <html:errors property="password" /> </font>
                </div>
                <html:submit property="submit" styleClass="form-control" value="Submit"/>
            </html:form>
        </div>

        <div class="right">
        <br>
            New User
            <a href="${pageContext.request.contextPath}/visitor/registration.do">Register Here</a>
            <br>
            <a href="${pageContext.request.contextPath}/visitor/forgotPassword.jsp">Forgot Passwod</a>
        </div>
    </body>
</html>